<#
  Builds the suglow.com deploy zip: the complete server-side codebase plus the
  compiled frontend - never storage/, .env or bootstrap/cache. It is the whole
  codebase rather than a list of changed files because the server has drifted
  behind the repo before, and a hand-picked list then shipped code calling
  classes the server did not have (see DEPLOY-BRANCH-STOCK.md).

  Run from anywhere, after `npm run build`:
    powershell -NoProfile -ExecutionPolicy Bypass -File make-zip.ps1 -Name POS-UPGRADE -Extra public/themes/default/css/custom.css

  -Extra adds any other file under public/ that the release touched.
#>
param(
    [Parameter(Mandatory = $true)][string]$Name,
    [string[]]$Extra = @()
)

$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot

if (-not (Test-Path (Join-Path $root 'public\build\manifest.json'))) {
    throw 'public/build/manifest.json is missing - run npm run build first'
}

# vite build empties public/build, so the caching rules are written back on
# every run. UTF-8 without a BOM and LF line endings: a BOM on the first line
# makes the web server reject the whole file. No trailing newline, so it stays
# byte-identical to the copy already proven on the server.
$htaccess = @'
# Immutable caching for Vite-fingerprinted assets. Regenerated by make-zip.ps1
# because vite build deletes this directory each run. Every file here carries a
# content hash, so caching forever can never serve stale code. No <If> because
# this host's LiteSpeed does not evaluate it inside <FilesMatch>.
<IfModule mod_headers.c>
    Header unset Cache-Control
    Header unset Pragma
    Header unset Expires
    Header always set Cache-Control "public, max-age=31536000, immutable"
</IfModule>
'@
$htaccess = $htaccess -replace "`r`n", "`n"
[System.IO.File]::WriteAllText((Join-Path $root 'public\build\.htaccess'), $htaccess, (New-Object System.Text.UTF8Encoding $false))

$dirs  = @('app', 'config', 'routes', 'lang', 'database\migrations', 'database\seeders', 'resources\views', 'public\build')
$files = @('bootstrap\app.php', 'bootstrap\providers.php', 'public\robots.txt', 'public\llms.txt') + $Extra

$entries = New-Object System.Collections.Generic.List[string]
foreach ($dir in $dirs) {
    Get-ChildItem -Path (Join-Path $root $dir) -Recurse -File -Force | ForEach-Object { $entries.Add($_.FullName) }
}
foreach ($file in $files) {
    $full = Join-Path $root ($file -replace '/', '\')
    if (-not (Test-Path $full -PathType Leaf)) {
        throw "missing file: $file"
    }
    $entries.Add((Resolve-Path $full).Path)
}

Add-Type -AssemblyName System.IO.Compression
Add-Type -AssemblyName System.IO.Compression.FileSystem

$zipPath = Join-Path $root "suglow-$Name.zip"
if (Test-Path $zipPath) {
    Remove-Item $zipPath -Force
}

$unique = $entries | Sort-Object -Unique
$zip = [System.IO.Compression.ZipFile]::Open($zipPath, [System.IO.Compression.ZipArchiveMode]::Create)
try {
    foreach ($full in $unique) {
        # Forward slashes. Compress-Archive writes backslashes, which the host's
        # unzip keeps as part of the file name: everything lands flat in one
        # folder and the site silently goes on serving the previous build.
        $rel = $full.Substring($root.Length + 1).Replace('\', '/')
        if ($rel -match '(^|/)\.env' -or $rel -match '^storage/' -or $rel -match '^bootstrap/cache/' -or $rel -match '\.sqlite$') {
            throw "refusing to pack $rel"
        }
        [void][System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile($zip, $full, $rel, [System.IO.Compression.CompressionLevel]::Optimal)
    }
} finally {
    $zip.Dispose()
}

Write-Output ("{0}: {1} entries, {2:N2} MB" -f (Split-Path $zipPath -Leaf), @($unique).Count, ((Get-Item $zipPath).Length / 1MB))
