import i18n from "../../../i18n";

/**
 * The Cash Calculation page's wording, English and Bangla.
 *
 * Kept here rather than in languages/*.json: en.json is part of the
 * storefront's entry chunk, and none of this is ever shown to a shopper. This
 * module is only pulled in with the admin page.
 */
const text = {
    en: {
        title: "Cash Calculation",
        settings: "Settings",
        today: "Today",
        shop_cash: "Shop cash",
        available_cash: "Available cash",
        closing_balance: "Closing balance",
        opening_balance: "Opening balance",
        pos_cash_sales: "POS cash sales",
        pos_reversed: "POS sales taken back",
        money_added: "Money added",
        withdrawn: "Withdrawn",
        transfer_in: "Transfer in",
        transfer_out: "Transfer out",
        count_difference: "Count difference",
        reversals: "Reversals",
        last_count: "Last count",
        never_counted: "Not counted yet",
        short: "short",
        over: "over",
        exact: "exact",
        non_cash_info: "Not in the drawer (for information)",
        card_sales: "Card",
        mfs_sales: "MFS payment",
        other_sales: "Other",
        bkash_agent: "bKash agent",
        nagad_agent: "Nagad agent",
        recharge_agent: "Recharge",
        sim: "SIM",
        balance: "Balance",
        cash: "Cash",
        sim_balance: "SIM balance",
        cash_in_hand: "Cash in hand",
        cash_in: "Cash In",
        cash_out: "Cash Out",
        recharge: "Recharge",
        total_sim_cash: "Total (SIM + cash)",
        closing: "Closing",
        grand_total: "Grand total",
        notes_total: "Notes (shop + bKash + Nagad + Recharge cash)",
        emoney_total: "E-money (bKash + Nagad SIM + Recharge balance)",
        total_branch_money: "Total branch money",
        add_money: "Add money",
        withdraw: "Withdraw",
        transfer: "Transfer",
        count: "Count",
        count_sim: "Count SIM",
        count_balance: "Count balance",
        count_cash: "Count cash",
        history: "History",
        my_entries_today: "My entries today",
        all_accounts: "All accounts",
        all_types: "All types",
        from: "From",
        to: "To",
        account: "Account",
        type: "Type",
        amount: "Amount",
        balance_after: "Balance after",
        by: "By",
        date: "Date",
        details: "Details",
        reverse: "Reverse",
        reversed: "reversed",
        no_entries: "No entries yet.",
        order: "Order",
        watch_list: "Watch list (last 7 days)",
        pos_reversals_alert: "POS cash sales taken back",
        minutes_after_sale: "{n} min after the sale",
        wrong_pin_alert: "Wrong PIN tries",
        tries: "{n} tries",
        short_counts_alert: "Short counts",
        nothing_to_watch: "Nothing unusual in the last 7 days.",
        default_pin_warning: "This branch still uses the default PIN. Change it so only you can take money out.",
        change_pin: "Change PIN",
        pin_locked: "Too many wrong PINs. PIN actions are locked for {n} minutes.",
        pin: "Branch PIN",
        current_pin: "Current PIN",
        new_pin: "New PIN (5-8 digits)",
        confirm_pin: "Confirm new PIN",
        mfs_service: "bKash / Nagad / Recharge service",
        mfs_on: "On",
        mfs_off: "Off",
        turn_on: "Turn on",
        turn_off: "Turn off",
        mfs_help: "When on, this branch gets separate bKash, Nagad and Recharge calculations.",
        note: "Note",
        reason: "Reason",
        given_to: "Given to",
        customer_number: "Customer number",
        trx_id: "Transaction ID",
        opening_chip: "Opening balance",
        commission_chip: "Agent commission",
        save: "Save",
        close: "Close",
        blind_count_help: "Count what is physically there. The expected amount is not shown.",
        sim_count_help: "Type the balance shown on the agent phone.",
        denomination: "Note / coin",
        pieces: "Pieces",
        counted_total: "Counted total",
        count_saved: "Count saved.",
        count_result: "Expected {e}, counted {c}, difference {d}.",
        saved: "Saved.",
        reverse_help: "This posts an opposite entry. The original stays in the history.",
        pin_changed: "PIN changed.",
        something_wrong: "Something went wrong.",
        no_branch: "No active branch found.",
        cashier_help: "Record money here. Balances are shown only to the owner.",
        needs_pin: "needs PIN",
        cash_in_help: "Customer gives cash, you send e-money: SIM -, cash +",
        cash_out_help: "Customer sends e-money, you give cash: SIM +, cash -",
        recharge_help: "Customer gives cash, you recharge their mobile: balance -, cash +",
        add: "Add",
        customer_number_short: "Number (optional)",
        amount_required: "Enter an amount.",
        mfs_quick_help: "In: SIM -, cash +. Out: SIM +, cash -.",
        mfs_quick_help_recharge: "Recharge: balance -, cash +.",
        mfs_off_title: "bKash / Nagad / Recharge is off for this branch",
        mfs_off_help: "Turn it on to keep separate bKash (In, Out), Nagad (In, Out) and Recharge calculations. Needs the branch PIN.",
        acc_1: "Shop cash",
        acc_2: "bKash SIM",
        acc_3: "bKash cash",
        acc_4: "Nagad SIM",
        acc_5: "Nagad cash",
        acc_6: "Recharge balance",
        acc_7: "Recharge cash",
        type_1: "POS sale",
        type_2: "POS sale taken back",
        type_3: "Added",
        type_4: "Withdrawn",
        type_5: "Transfer out",
        type_6: "Transfer in",
        type_7: "Cash In",
        type_8: "Cash Out",
        type_9: "Recharge",
        type_10: "Count difference",
        type_11: "Reversal",
    },
    bn: {
        title: "ক্যাশ হিসাব",
        settings: "সেটিংস",
        today: "আজ",
        shop_cash: "দোকানের ক্যাশ",
        available_cash: "বর্তমান ক্যাশ",
        closing_balance: "শেষ ব্যালেন্স",
        opening_balance: "শুরুর ব্যালেন্স",
        pos_cash_sales: "POS ক্যাশ বিক্রি",
        pos_reversed: "ফেরত নেওয়া POS বিক্রি",
        money_added: "টাকা যোগ",
        withdrawn: "টাকা উত্তোলন",
        transfer_in: "ট্রান্সফার এসেছে",
        transfer_out: "ট্রান্সফার গেছে",
        count_difference: "গণনার পার্থক্য",
        reversals: "রিভার্স",
        last_count: "শেষ গণনা",
        never_counted: "এখনো গণনা হয়নি",
        short: "কম",
        over: "বেশি",
        exact: "ঠিক আছে",
        non_cash_info: "ড্রয়ারে নেই (শুধু তথ্য)",
        card_sales: "কার্ড",
        mfs_sales: "MFS পেমেন্ট",
        other_sales: "অন্যান্য",
        bkash_agent: "বিকাশ এজেন্ট",
        nagad_agent: "নগদ এজেন্ট",
        recharge_agent: "রিচার্জ",
        sim: "সিম",
        balance: "ব্যালেন্স",
        cash: "ক্যাশ",
        sim_balance: "সিম ব্যালেন্স",
        cash_in_hand: "হাতে ক্যাশ",
        cash_in: "ক্যাশ ইন",
        cash_out: "ক্যাশ আউট",
        recharge: "রিচার্জ",
        total_sim_cash: "মোট (সিম + ক্যাশ)",
        closing: "শেষ",
        grand_total: "সর্বমোট",
        notes_total: "নগদ টাকা (দোকান + বিকাশ + নগদ + রিচার্জ ক্যাশ)",
        emoney_total: "ই-মানি (বিকাশ + নগদ সিম + রিচার্জ ব্যালেন্স)",
        total_branch_money: "শাখার মোট টাকা",
        add_money: "টাকা যোগ",
        withdraw: "উত্তোলন",
        transfer: "ট্রান্সফার",
        count: "গণনা",
        count_sim: "সিম গণনা",
        count_balance: "ব্যালেন্স গণনা",
        count_cash: "ক্যাশ গণনা",
        history: "ইতিহাস",
        my_entries_today: "আজ আমার এন্ট্রি",
        all_accounts: "সব অ্যাকাউন্ট",
        all_types: "সব ধরন",
        from: "থেকে",
        to: "পর্যন্ত",
        account: "অ্যাকাউন্ট",
        type: "ধরন",
        amount: "পরিমাণ",
        balance_after: "পরের ব্যালেন্স",
        by: "করেছেন",
        date: "তারিখ",
        details: "বিস্তারিত",
        reverse: "রিভার্স",
        reversed: "রিভার্স হয়েছে",
        no_entries: "এখনো কোনো এন্ট্রি নেই।",
        order: "অর্ডার",
        watch_list: "নজরদারি (গত ৭ দিন)",
        pos_reversals_alert: "ফেরত নেওয়া POS ক্যাশ বিক্রি",
        minutes_after_sale: "বিক্রির {n} মিনিট পর",
        wrong_pin_alert: "ভুল পিন চেষ্টা",
        tries: "{n} বার",
        short_counts_alert: "কম পাওয়া গণনা",
        nothing_to_watch: "গত ৭ দিনে অস্বাভাবিক কিছু নেই।",
        default_pin_warning: "এই শাখা এখনো ডিফল্ট পিন ব্যবহার করছে। শুধু আপনি যেন টাকা তুলতে পারেন, পিন পরিবর্তন করুন।",
        change_pin: "পিন পরিবর্তন",
        pin_locked: "অনেকবার ভুল পিন। {n} মিনিট পিন লাগে এমন কাজ বন্ধ থাকবে।",
        pin: "শাখার পিন",
        current_pin: "বর্তমান পিন",
        new_pin: "নতুন পিন (৫-৮ সংখ্যা)",
        confirm_pin: "নতুন পিন আবার লিখুন",
        mfs_service: "বিকাশ / নগদ / রিচার্জ সেবা",
        mfs_on: "চালু",
        mfs_off: "বন্ধ",
        turn_on: "চালু করুন",
        turn_off: "বন্ধ করুন",
        mfs_help: "চালু থাকলে এই শাখায় বিকাশ, নগদ ও রিচার্জের আলাদা হিসাব থাকবে।",
        note: "নোট",
        reason: "কারণ",
        given_to: "কাকে দেওয়া হলো",
        customer_number: "গ্রাহকের নম্বর",
        trx_id: "ট্রানজেকশন আইডি",
        opening_chip: "শুরুর ব্যালেন্স",
        commission_chip: "এজেন্ট কমিশন",
        save: "সংরক্ষণ",
        close: "বন্ধ",
        blind_count_help: "বাস্তবে যা আছে তা গুনুন। প্রত্যাশিত পরিমাণ দেখানো হবে না।",
        sim_count_help: "এজেন্ট ফোনে দেখানো ব্যালেন্স লিখুন।",
        denomination: "নোট / কয়েন",
        pieces: "সংখ্যা",
        counted_total: "গণনার মোট",
        count_saved: "গণনা সংরক্ষিত হয়েছে।",
        count_result: "প্রত্যাশিত {e}, গণনা {c}, পার্থক্য {d}।",
        saved: "সংরক্ষিত হয়েছে।",
        reverse_help: "এটি একটি বিপরীত এন্ট্রি দেবে। আগের এন্ট্রি ইতিহাসে থেকে যাবে।",
        pin_changed: "পিন পরিবর্তন হয়েছে।",
        something_wrong: "কিছু একটা ভুল হয়েছে।",
        no_branch: "কোনো সক্রিয় শাখা পাওয়া যায়নি।",
        cashier_help: "এখানে টাকার হিসাব লিখুন। ব্যালেন্স শুধু মালিক দেখতে পারবেন।",
        needs_pin: "পিন লাগবে",
        cash_in_help: "গ্রাহক ক্যাশ দেন, আপনি ই-মানি পাঠান: সিম -, ক্যাশ +",
        cash_out_help: "গ্রাহক ই-মানি পাঠান, আপনি ক্যাশ দেন: সিম +, ক্যাশ -",
        recharge_help: "গ্রাহক ক্যাশ দেন, আপনি মোবাইল রিচার্জ করেন: ব্যালেন্স -, ক্যাশ +",
        add: "যোগ",
        customer_number_short: "নম্বর (ঐচ্ছিক)",
        amount_required: "টাকার পরিমাণ লিখুন।",
        mfs_quick_help: "ইন: সিম -, ক্যাশ +। আউট: সিম +, ক্যাশ -।",
        mfs_quick_help_recharge: "রিচার্জ: ব্যালেন্স -, ক্যাশ +।",
        mfs_off_title: "এই শাখায় বিকাশ / নগদ / রিচার্জ বন্ধ আছে",
        mfs_off_help: "চালু করলে বিকাশ (ইন, আউট), নগদ (ইন, আউট) ও রিচার্জের আলাদা হিসাব থাকবে। শাখার পিন লাগবে।",
        acc_1: "দোকানের ক্যাশ",
        acc_2: "বিকাশ সিম",
        acc_3: "বিকাশ ক্যাশ",
        acc_4: "নগদ সিম",
        acc_5: "নগদ ক্যাশ",
        acc_6: "রিচার্জ ব্যালেন্স",
        acc_7: "রিচার্জ ক্যাশ",
        type_1: "POS বিক্রি",
        type_2: "POS বিক্রি ফেরত",
        type_3: "যোগ",
        type_4: "উত্তোলন",
        type_5: "ট্রান্সফার গেছে",
        type_6: "ট্রান্সফার এসেছে",
        type_7: "ক্যাশ ইন",
        type_8: "ক্যাশ আউট",
        type_9: "রিচার্জ",
        type_10: "গণনার পার্থক্য",
        type_11: "রিভার্স",
    },
};

export function tr(key, params = {}) {
    const locale = i18n.global.locale.value;
    let value = (text[locale] && text[locale][key]) || text.en[key] || key;

    Object.keys(params).forEach((name) => {
        value = value.replace("{" + name + "}", params[name]);
    });

    return value;
}

export const ACCOUNT = { DRAWER: 1, BKASH_SIM: 2, BKASH_CASH: 3, NAGAD_SIM: 4, NAGAD_CASH: 5, RECHARGE_SIM: 6, RECHARGE_CASH: 7 };

export const ALL_ACCOUNTS = [1, 2, 3, 4, 5, 6, 7];

// Recharge is a service of its own, next to bKash and Nagad - not something
// either of them does.
export const PROVIDERS = ["bkash", "nagad", "recharge"];

export const KINDS = {
    bkash: ["cash_in", "cash_out"],
    nagad: ["cash_in", "cash_out"],
    recharge: ["recharge"],
};

// Whole class names, so Tailwind finds them when it scans this file.
export const THEME = {
    bkash: { title: "text-pink-600", label: "text-pink-700", button: "bg-pink-600", box: "border-pink-200 bg-pink-50/40" },
    nagad: { title: "text-orange-600", label: "text-orange-700", button: "bg-orange-500", box: "border-orange-200 bg-orange-50/40" },
    recharge: { title: "text-sky-600", label: "text-sky-700", button: "bg-sky-600", box: "border-sky-200 bg-sky-50/40" },
};

export const MFS = {
    bkash: { sim: ACCOUNT.BKASH_SIM, cash: ACCOUNT.BKASH_CASH },
    nagad: { sim: ACCOUNT.NAGAD_SIM, cash: ACCOUNT.NAGAD_CASH },
    recharge: { sim: ACCOUNT.RECHARGE_SIM, cash: ACCOUNT.RECHARGE_CASH },
};

export const SIM_ACCOUNTS = [ACCOUNT.BKASH_SIM, ACCOUNT.NAGAD_SIM, ACCOUNT.RECHARGE_SIM];
