import i18n from "../../../i18n";

/**
 * The Cash Calculation page's wording, English and Bangla.
 *
 * Kept here rather than in languages/*.json: en.json is part of the
 * storefront's entry chunk, and none of this is ever shown to a shopper. This
 * module is only pulled in with the admin page.
 */
const text = {
    en: {
        title: "Cash Calculation",
        settings: "Settings",
        today: "Today",
        shop_cash: "Cash drawer (notes)",
        drawer_help: "Notes and coins only: POS cash sales and money added.",
        emoney_title: "POS e-money (card & MFS)",
        emoney_help: "Till sales paid by card or by bKash/Nagad at the counter. Never in the drawer.",
        card_col: "Card",
        mfs_col: "MFS",
        pos_sales: "POS sales",
        total_card_mfs: "Card + MFS",
        counts_title: "Counts on this day",
        count_correct: "Congratulations! Your count matches - the calculation is correct.",
        count_wrong: "The count does not match the calculation. Count again carefully and think again.",
        count_again: "Count again",
        result_col: "Result",
        matched_word: "Correct",
        not_matched_word: "Not matched",
        transactions_on: "Transactions on {d}",
        my_counts_today: "My counts today",
        count_is_check: "Counts only check the calculation; balances never change from a count.",
        no_counts: "No counts on this day.",
        notes_counted: "Notes counted",
        expected: "Expected",
        difference: "Difference",
        counted_word: "Counted",
        typed_balance: "typed balance",
        acc_8: "Card (POS)",
        acc_9: "MFS payment (POS)",
        available_cash: "Available cash",
        closing_balance: "Closing balance",
        opening_balance: "Opening balance",
        pos_cash_sales: "POS cash sales",
        pos_reversed: "POS sales taken back",
        money_added: "Money added",
        withdrawn: "Withdrawn",
        transfer_in: "Transfer in",
        transfer_out: "Transfer out",
        count_difference: "Count difference",
        reversals: "Reversals",
        last_count: "Last count",
        never_counted: "Not counted yet",
        short: "short",
        over: "over",
        exact: "exact",
        non_cash_info: "Not in the drawer (for information)",
        card_sales: "Card",
        mfs_sales: "MFS payment",
        other_sales: "Other payment",
        bkash_agent: "bKash agent",
        nagad_agent: "Nagad agent",
        recharge_agent: "Recharge",
        sim: "SIM",
        balance: "Balance",
        cash: "Cash",
        sim_balance: "SIM balance",
        cash_in_hand: "Cash in hand",
        cash_in: "Cash In",
        cash_out: "Cash Out",
        recharge: "Recharge",
        total_sim_cash: "Total (SIM + cash)",
        closing: "Closing",
        grand_total: "Grand total",
        notes_total: "Notes (drawer + bKash / Nagad / Recharge cash)",
        emoney_total: "E-money (POS card & MFS + SIM balances)",
        total_branch_money: "Total branch money",
        add_money: "Add money",
        withdraw: "Withdraw",
        transfer: "Transfer",
        count: "Count",
        count_all_cash: "Count all cash",
        all_cash_in_drawer: "All cash in the drawer",
        all_cash_help: "Shop cash + bKash, Nagad and Recharge cash - what a count should find.",
        whole_drawer_help: "Count every note in the drawer - shop cash and bKash, Nagad and Recharge cash together. The count only checks the calculation - it never changes the balance.",
        history: "History",
        my_entries_today: "My entries today",
        all_accounts: "All accounts",
        all_types: "All types",
        from: "From",
        to: "To",
        account: "Account",
        type: "Type",
        amount: "Amount",
        balance_after: "Balance after",
        by: "By",
        date: "Date",
        details: "Details",
        reverse: "Reverse",
        reversed: "reversed",
        no_entries: "No entries yet.",
        order: "Order",
        watch_list: "Watch list",
        last_7_days: "Last 7 days",
        pos_reversals_alert: "POS cash sales taken back",
        minutes_after_sale: "{n} min after the sale",
        wrong_pin_alert: "Wrong PIN tries",
        tries: "{n} tries",
        short_counts_alert: "Counts that did not match",
        nothing_to_watch: "Nothing unusual in the last 7 days.",
        nothing_today: "Nothing unusual today.",
        default_pin_warning: "This branch still uses the default PIN. Change it so only you can take money out.",
        change_pin: "Change PIN",
        pin_locked: "Too many wrong PINs. PIN actions are locked for {n} minutes.",
        pin: "Branch PIN",
        current_pin: "Current PIN",
        new_pin: "New PIN (5-8 digits)",
        confirm_pin: "Confirm new PIN",
        mfs_service: "bKash / Nagad / Recharge service",
        mfs_on: "On",
        mfs_off: "Off",
        turn_on: "Turn on",
        turn_off: "Turn off",
        mfs_help: "When on, this branch gets separate bKash, Nagad and Recharge calculations.",
        note: "Note",
        reason: "Reason",
        given_to: "Given to",
        customer_number: "Customer number",
        trx_id: "Transaction ID",
        opening_chip: "Opening balance",
        commission_chip: "Agent commission",
        save: "Save",
        close: "Close",
        blind_count_help: "Count the notes that are physically there. The count only checks the calculation - it never changes the balance.",
        sim_count_help: "Type the balance shown on the phone or statement.",
        denomination: "Note / coin",
        pieces: "Pieces",
        counted_total: "Counted total",
        count_saved: "Count recorded",
        count_result: "Expected {e}, counted {c}, difference {d}.",
        saved: "Saved.",
        success_add: "Money added",
        success_cash_in: "Cash In saved",
        success_cash_out: "Cash Out saved",
        success_recharge: "Recharge saved",
        saved_tick: "Saved",
        reverse_help: "This posts an opposite entry. The original stays in the history.",
        pin_changed: "PIN changed.",
        something_wrong: "Something went wrong.",
        no_branch: "No active branch found.",
        cashier_help: "Record money here. Balances are shown only to the owner.",
        needs_pin: "needs PIN",
        cash_in_help: "Customer gives cash, you send e-money: SIM -, cash +",
        cash_out_help: "Customer sends e-money, you give cash: SIM +, cash -",
        recharge_help: "Customer gives cash, you recharge their mobile: balance -, cash +",
        add: "Add",
        customer_number_short: "Number (optional)",
        amount_required: "Enter an amount.",
        mfs_quick_help: "In: SIM -, cash +. Out: SIM +, cash -.",
        mfs_quick_help_recharge: "Recharge: balance -, cash +.",
        acc_1: "Cash drawer",
        acc_2: "bKash SIM",
        acc_3: "bKash cash",
        acc_4: "Nagad SIM",
        acc_5: "Nagad cash",
        acc_6: "Recharge balance",
        acc_7: "Recharge cash",
        type_1: "POS sale",
        type_2: "POS sale taken back",
        type_3: "Added",
        type_4: "Withdrawn",
        type_5: "Transfer out",
        type_6: "Transfer in",
        type_7: "Cash In",
        type_8: "Cash Out",
        type_9: "Recharge",
        type_10: "Count difference",
        type_11: "Reversal",
        type_12: "Reset to zero",
        reset_line: "Reset to zero",
        counted_by: "Counted by",
        choose_counter: "Choose who counted",
        choose_counter_first: "Choose who counted the money.",
        reset_title: "Reset this branch to zero",
        reset_help: "Every balance of this branch - shop cash, card / MFS, bKash, Nagad and Recharge - becomes 0. The history stays; the reset is written in it as its own line.",
        reset_confirm: "I understand every balance of {branch} becomes 0.",
        reset_button: "Reset to zero",
        reset_done: "Done. {n} balances set to 0.",
        reset_nothing: "Everything was already 0.",
        updating: "Updating…",
        offline_banner: "No internet. Showing the figures from {t}. Saving needs a connection.",
        offline_short: "No internet connection.",
        load_failed: "Could not reach the server.",
        figures_from: "Showing the figures from {t}.",
        try_again: "Try again",
        network_retry: "No answer from the server. Nothing is lost - tap again; it will not be saved twice.",
    },
    bn: {
        title: "ক্যাশ হিসাব",
        settings: "সেটিংস",
        today: "আজ",
        shop_cash: "ক্যাশ ড্রয়ার (নোট)",
        drawer_help: "শুধু নোট ও কয়েন: POS ক্যাশ বিক্রি ও যোগ করা টাকা।",
        emoney_title: "POS ই-মানি (কার্ড ও MFS)",
        emoney_help: "কাউন্টারে কার্ড বা বিকাশ/নগদ দিয়ে পরিশোধ করা বিক্রি। কখনো ড্রয়ারে থাকে না।",
        card_col: "কার্ড",
        mfs_col: "MFS",
        pos_sales: "POS বিক্রি",
        total_card_mfs: "কার্ড + MFS",
        counts_title: "এই দিনের গণনা",
        count_correct: "অভিনন্দন! আপনার গণনা মিলেছে - হিসাব সঠিক।",
        count_wrong: "গণনা হিসাবের সাথে মেলেনি। আবার সাবধানে গুনে দেখুন এবং ভেবে দেখুন।",
        count_again: "আবার গুনুন",
        result_col: "ফলাফল",
        matched_word: "সঠিক",
        not_matched_word: "মেলেনি",
        transactions_on: "{d} তারিখের লেনদেন",
        my_counts_today: "আজ আমার গণনা",
        count_is_check: "গণনা শুধু হিসাব মেলায়; গণনার কারণে কখনো ব্যালেন্স বদলায় না।",
        no_counts: "এই দিনে কোনো গণনা হয়নি।",
        notes_counted: "গোনা নোট",
        expected: "প্রত্যাশিত",
        difference: "পার্থক্য",
        counted_word: "গণনা",
        typed_balance: "লেখা ব্যালেন্স",
        acc_8: "কার্ড (POS)",
        acc_9: "MFS পেমেন্ট (POS)",
        available_cash: "বর্তমান ক্যাশ",
        closing_balance: "শেষ ব্যালেন্স",
        opening_balance: "শুরুর ব্যালেন্স",
        pos_cash_sales: "POS ক্যাশ বিক্রি",
        pos_reversed: "ফেরত নেওয়া POS বিক্রি",
        money_added: "টাকা যোগ",
        withdrawn: "টাকা উত্তোলন",
        transfer_in: "ট্রান্সফার এসেছে",
        transfer_out: "ট্রান্সফার গেছে",
        count_difference: "গণনার পার্থক্য",
        reversals: "রিভার্স",
        last_count: "শেষ গণনা",
        never_counted: "এখনো গণনা হয়নি",
        short: "কম",
        over: "বেশি",
        exact: "ঠিক আছে",
        non_cash_info: "ড্রয়ারে নেই (শুধু তথ্য)",
        card_sales: "কার্ড",
        mfs_sales: "MFS পেমেন্ট",
        other_sales: "অন্যান্য পেমেন্ট",
        bkash_agent: "বিকাশ এজেন্ট",
        nagad_agent: "নগদ এজেন্ট",
        recharge_agent: "রিচার্জ",
        sim: "সিম",
        balance: "ব্যালেন্স",
        cash: "ক্যাশ",
        sim_balance: "সিম ব্যালেন্স",
        cash_in_hand: "হাতে ক্যাশ",
        cash_in: "ক্যাশ ইন",
        cash_out: "ক্যাশ আউট",
        recharge: "রিচার্জ",
        total_sim_cash: "মোট (সিম + ক্যাশ)",
        closing: "শেষ",
        grand_total: "সর্বমোট",
        notes_total: "নগদ নোট (ড্রয়ার + বিকাশ / নগদ / রিচার্জ ক্যাশ)",
        emoney_total: "ই-মানি (POS কার্ড ও MFS + সিম ব্যালেন্স)",
        total_branch_money: "শাখার মোট টাকা",
        add_money: "টাকা যোগ",
        withdraw: "উত্তোলন",
        transfer: "ট্রান্সফার",
        count: "গণনা",
        count_all_cash: "সব ক্যাশ গুনুন",
        all_cash_in_drawer: "ড্রয়ারের সব ক্যাশ",
        all_cash_help: "দোকানের ক্যাশ + বিকাশ, নগদ ও রিচার্জ ক্যাশ - গুনলে এটাই পাওয়ার কথা।",
        whole_drawer_help: "ড্রয়ারের সব নোট গুনুন - দোকানের ক্যাশ আর বিকাশ, নগদ ও রিচার্জ ক্যাশ একসাথে। গণনা শুধু হিসাব মেলায় - কখনো ব্যালেন্স বদলায় না।",
        history: "ইতিহাস",
        my_entries_today: "আজ আমার এন্ট্রি",
        all_accounts: "সব অ্যাকাউন্ট",
        all_types: "সব ধরন",
        from: "থেকে",
        to: "পর্যন্ত",
        account: "অ্যাকাউন্ট",
        type: "ধরন",
        amount: "পরিমাণ",
        balance_after: "পরের ব্যালেন্স",
        by: "করেছেন",
        date: "তারিখ",
        details: "বিস্তারিত",
        reverse: "রিভার্স",
        reversed: "রিভার্স হয়েছে",
        no_entries: "এখনো কোনো এন্ট্রি নেই।",
        order: "অর্ডার",
        watch_list: "নজরদারি",
        last_7_days: "গত ৭ দিন",
        pos_reversals_alert: "ফেরত নেওয়া POS ক্যাশ বিক্রি",
        minutes_after_sale: "বিক্রির {n} মিনিট পর",
        wrong_pin_alert: "ভুল পিন চেষ্টা",
        tries: "{n} বার",
        short_counts_alert: "যে গণনা মেলেনি",
        nothing_to_watch: "গত ৭ দিনে অস্বাভাবিক কিছু নেই।",
        nothing_today: "আজ অস্বাভাবিক কিছু নেই।",
        default_pin_warning: "এই শাখা এখনো ডিফল্ট পিন ব্যবহার করছে। শুধু আপনি যেন টাকা তুলতে পারেন, পিন পরিবর্তন করুন।",
        change_pin: "পিন পরিবর্তন",
        pin_locked: "অনেকবার ভুল পিন। {n} মিনিট পিন লাগে এমন কাজ বন্ধ থাকবে।",
        pin: "শাখার পিন",
        current_pin: "বর্তমান পিন",
        new_pin: "নতুন পিন (৫-৮ সংখ্যা)",
        confirm_pin: "নতুন পিন আবার লিখুন",
        mfs_service: "বিকাশ / নগদ / রিচার্জ সেবা",
        mfs_on: "চালু",
        mfs_off: "বন্ধ",
        turn_on: "চালু করুন",
        turn_off: "বন্ধ করুন",
        mfs_help: "চালু থাকলে এই শাখায় বিকাশ, নগদ ও রিচার্জের আলাদা হিসাব থাকবে।",
        note: "নোট",
        reason: "কারণ",
        given_to: "কাকে দেওয়া হলো",
        customer_number: "গ্রাহকের নম্বর",
        trx_id: "ট্রানজেকশন আইডি",
        opening_chip: "শুরুর ব্যালেন্স",
        commission_chip: "এজেন্ট কমিশন",
        save: "সংরক্ষণ",
        close: "বন্ধ",
        blind_count_help: "বাস্তবে যে নোট আছে তা গুনুন। গণনা শুধু হিসাব মেলায় - কখনো ব্যালেন্স বদলায় না।",
        sim_count_help: "ফোন বা স্টেটমেন্টে দেখানো ব্যালেন্স লিখুন।",
        denomination: "নোট / কয়েন",
        pieces: "সংখ্যা",
        counted_total: "গণনার মোট",
        count_saved: "গণনা সংরক্ষিত হয়েছে",
        count_result: "প্রত্যাশিত {e}, গণনা {c}, পার্থক্য {d}।",
        saved: "সংরক্ষিত হয়েছে।",
        success_add: "টাকা যোগ হয়েছে",
        success_cash_in: "ক্যাশ ইন সংরক্ষিত",
        success_cash_out: "ক্যাশ আউট সংরক্ষিত",
        success_recharge: "রিচার্জ সংরক্ষিত",
        saved_tick: "সংরক্ষিত",
        reverse_help: "এটি একটি বিপরীত এন্ট্রি দেবে। আগের এন্ট্রি ইতিহাসে থেকে যাবে।",
        pin_changed: "পিন পরিবর্তন হয়েছে।",
        something_wrong: "কিছু একটা ভুল হয়েছে।",
        no_branch: "কোনো সক্রিয় শাখা পাওয়া যায়নি।",
        cashier_help: "এখানে টাকার হিসাব লিখুন। ব্যালেন্স শুধু মালিক দেখতে পারবেন।",
        needs_pin: "পিন লাগবে",
        cash_in_help: "গ্রাহক ক্যাশ দেন, আপনি ই-মানি পাঠান: সিম -, ক্যাশ +",
        cash_out_help: "গ্রাহক ই-মানি পাঠান, আপনি ক্যাশ দেন: সিম +, ক্যাশ -",
        recharge_help: "গ্রাহক ক্যাশ দেন, আপনি মোবাইল রিচার্জ করেন: ব্যালেন্স -, ক্যাশ +",
        add: "যোগ",
        customer_number_short: "নম্বর (ঐচ্ছিক)",
        amount_required: "টাকার পরিমাণ লিখুন।",
        mfs_quick_help: "ইন: সিম -, ক্যাশ +। আউট: সিম +, ক্যাশ -।",
        mfs_quick_help_recharge: "রিচার্জ: ব্যালেন্স -, ক্যাশ +।",
        acc_1: "ক্যাশ ড্রয়ার",
        acc_2: "বিকাশ সিম",
        acc_3: "বিকাশ ক্যাশ",
        acc_4: "নগদ সিম",
        acc_5: "নগদ ক্যাশ",
        acc_6: "রিচার্জ ব্যালেন্স",
        acc_7: "রিচার্জ ক্যাশ",
        type_1: "POS বিক্রি",
        type_2: "POS বিক্রি ফেরত",
        type_3: "যোগ",
        type_4: "উত্তোলন",
        type_5: "ট্রান্সফার গেছে",
        type_6: "ট্রান্সফার এসেছে",
        type_7: "ক্যাশ ইন",
        type_8: "ক্যাশ আউট",
        type_9: "রিচার্জ",
        type_10: "গণনার পার্থক্য",
        type_11: "রিভার্স",
        type_12: "শূন্যে রিসেট",
        reset_line: "শূন্যে রিসেট",
        counted_by: "গুনেছেন",
        choose_counter: "কে গুনেছেন বেছে নিন",
        choose_counter_first: "কে টাকা গুনেছেন বেছে নিন।",
        reset_title: "এই শাখা শূন্যে রিসেট",
        reset_help: "এই শাখার সব ব্যালেন্স - দোকানের ক্যাশ, কার্ড / MFS, বিকাশ, নগদ ও রিচার্জ - ০ হয়ে যাবে। হিস্টোরি থাকবে; রিসেট সেখানে আলাদা লাইন হিসেবে লেখা হবে।",
        reset_confirm: "আমি বুঝেছি {branch} এর সব ব্যালেন্স ০ হয়ে যাবে।",
        reset_button: "শূন্যে রিসেট",
        reset_done: "হয়েছে। {n}টি ব্যালেন্স ০ করা হয়েছে।",
        reset_nothing: "সবকিছু আগেই ০ ছিল।",
        updating: "আপডেট হচ্ছে…",
        offline_banner: "ইন্টারনেট নেই। {t} এর হিসাব দেখানো হচ্ছে। সেভ করতে সংযোগ লাগবে।",
        offline_short: "ইন্টারনেট সংযোগ নেই।",
        load_failed: "সার্ভারে পৌঁছানো যায়নি।",
        figures_from: "{t} এর হিসাব দেখানো হচ্ছে।",
        try_again: "আবার চেষ্টা করুন",
        network_retry: "সার্ভার থেকে উত্তর আসেনি। কিছু হারায়নি - আবার চাপুন; দুইবার সেভ হবে না।",
    },
};

export function tr(key, params = {}) {
    const locale = i18n.global.locale.value;
    let value = (text[locale] && text[locale][key]) || text.en[key] || key;

    Object.keys(params).forEach((name) => {
        value = value.replace("{" + name + "}", params[name]);
    });

    return value;
}

export const ACCOUNT = { DRAWER: 1, BKASH_SIM: 2, BKASH_CASH: 3, NAGAD_SIM: 4, NAGAD_CASH: 5, RECHARGE_SIM: 6, RECHARGE_CASH: 7, POS_CARD: 8, POS_MFS: 9 };

export const ALL_ACCOUNTS = [1, 8, 9, 2, 3, 4, 5, 6, 7];

// Always there: the drawer and the till's card / MFS e-money. The agent
// accounts join them while the branch has agent service on.
export const BASE_ACCOUNTS = [1, 8, 9];

// Held as notes and coins, so counted note by note. The rest is e-money and
// counted by typing the balance.
export const NOTE_ACCOUNTS = [1, 3, 5, 7];

// Recharge is a service of its own, next to bKash and Nagad - not something
// either of them does.
export const PROVIDERS = ["bkash", "nagad", "recharge"];

export const KINDS = {
    bkash: ["cash_in", "cash_out"],
    nagad: ["cash_in", "cash_out"],
    recharge: ["recharge"],
};

// Whole class names, so Tailwind finds them when it scans this file.
export const THEME = {
    bkash: { title: "text-pink-600", label: "text-pink-700", button: "bg-pink-600", box: "border-pink-200 bg-pink-50/40" },
    nagad: { title: "text-orange-600", label: "text-orange-700", button: "bg-orange-500", box: "border-orange-200 bg-orange-50/40" },
    recharge: { title: "text-sky-600", label: "text-sky-700", button: "bg-sky-600", box: "border-sky-200 bg-sky-50/40" },
};

export const MFS = {
    bkash: { sim: ACCOUNT.BKASH_SIM, cash: ACCOUNT.BKASH_CASH },
    nagad: { sim: ACCOUNT.NAGAD_SIM, cash: ACCOUNT.NAGAD_CASH },
    recharge: { sim: ACCOUNT.RECHARGE_SIM, cash: ACCOUNT.RECHARGE_CASH },
};

export const SIM_ACCOUNTS = [ACCOUNT.BKASH_SIM, ACCOUNT.NAGAD_SIM, ACCOUNT.RECHARGE_SIM];
